### ISSUE TITLE
[feat] 아지트 생성 기능 구현

### ISSUE THREAD

**Issue by KISOOJIN** [codestates-seb/seb41_main_004#101]
## Description
통신 테스트를 제외한 아지트 생성 기능을 구현한다.

## Todo
- [x] 이미지 업로드 및 미리보기 구현( 크롭을 해야하는데 가능할지... 시도는 하고 있으나 어려워 보임...)
- [x] 아지트 이름 글자 수 최대 24자 제한 걸어두기
- [x] 아지트 소개해주세요. textara max 128자 제한 걸어두기
- [x] 오프라인 선택시 다음 주소 api를 통해 장소 값 받아와서 입력 값에 넣기
- [x] 제한 없음 클릭시 select창 비활성화
- [x] 참가비 입력창 단위 입력되게 만들기
- [x] 모든 입력 창 값 완료시 button active 되게 구현

## Duration
1~2 d
