### ISSUE TITLE
[feat] userpage 기능 구현

### ISSUE THREAD

**Issue by FE012** [codestates-seb/seb41_main_004#103]
## Description
통신 테스트를 포함한 userpage를 구현한다

## Todo
- [x] 마이페이지이면 프로필 수정과 설정 아이콘이 보이도록 하고, 유저 페이지면 신고 아이콘과 팔로우 버튼이 보이도록 하기
- [x] 통신테스트 및 유저정보 데이터 받아오기
- [x] 활동내역중 호스트인 아지트만 보이게 하기
- [x]  활동내역중 전체보기, 신청한 모임, 참여중인 모임, 종료된 모임 상태에 따라 보이게 하기
