### ISSUE TITLE
[feat] 일반 로그인 기능 구현

### ISSUE THREAD

**Issue by zoeypark** [codestates-seb/seb41_main_004#106]
## Description
- 유저 로그인 기능을 구현합니다.

## Todo
- [x] 통신 코드 작성
- [x] 로컬스토리지 저장 기능 구현
- [x] 로그인 상태 변경 코드 작성
- [x] 로그인 상태 변경 테스트
- [x] 에러 핸들링
- [ ] 토큰 재발급 기능 구현
