### ISSUE TITLE
[feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by zoeypark** [codestates-seb/seb41_main_004#110]
## Description
- 회원 가입 기능을 구현합니다.

## Todo
- Signup 페이지
- [x] 클라이언트에서의 유효성 검사 구현
- [x] 닉네임 중복 검사 기능 구현
- [x] 모든 항목에서 유효성 검사 통과했을 때만 '추가 정보 입력' 버튼이 활성화되는 기능 구현
- [x] 작성된 data를 SignupAdditional 페이지로 가져가는 기능 구현 (백엔드와 논의 필요)
- SignupAdditional 페이지
- [x] Profile image 업로드 기능 구현
- [x] 회원 가입 통신 기능 구현
