### ISSUE TITLE
[feat] 검색 페이지 기능 구현

### ISSUE THREAD

**Issue by CHOGANGYEOL** [codestates-seb/seb41_main_004#122]
## Description
검색 페이지 기능 구현

## Todo
- [x] 검색 페이지 내부 state 관리
- [x] api요청으로 검색결과 확인
- [x] 기존 더미데이터와 맞춰 에러 수정
- [x] 무한스크롤 구현
