### ISSUE TITLE
[Club/Member] 아지트 참가 및 승인, 거절, 강퇴 기능 구현

### ISSUE THREAD

**Issue by my-roki** [codestates-seb/seb41_main_004#125]
## Description
생성된 아지트에 유저가 참여하고 호스트가 신청, 거절, 참여하고 있는 유저를 강퇴시킬 수 있는 기능을 구현합니다.

## Todo
- [x] 참여 정보를 담는 ClubMember entity 및 repository 작성 
- [x] 각 기능별 api 컨트롤러 작성 및 서비스 로직 구현
- [x] 테스트 코드 작성 및 api 문서화

## Duration
1d
