### ISSUE TITLE
[club] 아지트 CRUD 구현

### ISSUE THREAD

**Issue by my-roki** [codestates-seb/seb41_main_004#16]
## Description
아지트와 관련된 CRUD 기본적인 코드를 구현합니다.

## Todo
- [x] Club Entity 및 Repository 작성
- [x] Club Controller 및 dto 작성
- [x] Club Crud를 구현한 Service 코드 구현
- [x] Club Crud 관련된 테스트 코드 작성 및 api 문서 작성

## Duration
1d
