### ISSUE TITLE
[common] 도메인 공통기능 구현

### ISSUE THREAD

**Issue by my-roki** [codestates-seb/seb41_main_004#22]
## Description
백엔드 개발할 때 필요한 공통기능을 구현합니다. 공통 기능을 정해놓음으로써 통일되는 값을 주고 받을 수 있습니다.

## Todo
- [ ] Entity 공통 컬럼 BaseEntity 구현 
- [ ] 공통 ResponseDto 구현(Single, Multi)
- [ ] Update에 필요한 Beanitils 구현
- [ ] null값 처리를 위한 ObjectMapperBuilder 구현

## Duration
0.5d
