### ISSUE TITLE
[member] entity, dto, controller(empty) 만들기

### ISSUE THREAD

**Issue by hionpu** [codestates-seb/seb41_main_004#25]
## Description
member entity, DTO와 깡통 controller 틀을 만들기

## Todo
- [ ]  member Entity 작성
- [ ]  member DTO 작성
- [ ]  member Controller 작성

## Duration
1d
