### ISSUE TITLE
[review] entity, DTO, controller(empty) 만들기

### ISSUE THREAD

**Issue by hionpu** [codestates-seb/seb41_main_004#26]
## Description
review entity, DTO와 깡통 controller 틀을 만들기

## Todo
- [ ]  review Entity 작성
- [ ]  review DTO 작성
- [ ]  review Controller 작성

## Duration
1d
