### ISSUE TITLE
[auth] 일반 회원 로그인 인증 구현

### ISSUE THREAD

**Issue by yeonini** [codestates-seb/seb41_main_004#8]
## Description
 JWT를 이용한 일반 회원 로그인 인증 기능 구현

## Todo
- [ ] JWT 생성
- [ ] 로그인 인증 구현
- [ ] 인증 성공/실패 처리
- [ ] 자격 증명 및 검증
- [ ] 권한 설정
- [ ] 예외 처리

## Duration
5d - 금요일 1차 배포 때까지 완료
