### ISSUE TITLE
[Category] 관심사 카테고리 관련 코드 구현

### ISSUE THREAD

**Issue by my-roki** [codestates-seb/seb41_main_004#80]
## Description
관심사 카테고리 관련 코드를 구현합니다.

## Todo
- [ ] 소분류, 대분류 category 각각 entity 구현
- [ ] 각각의 카테고리를 조회할 수 있는 api 컨트롤러 구현
- [ ] 카테고리 조회를 위한 서비스 로직 구현

## Duration
ex) 1d
