### ISSUE TITLE
[exception] 공통 예외처리 부분 구현

### ISSUE THREAD

**Issue by my-roki** [codestates-seb/seb41_main_004#9]
## Description
서버쪽 예외상황 발생시 예외상황을 처리하는 핸들러를 구현합니다.

## Todo
- [ ] 예외처리를 받을 Exception class 구현
- [ ] exception code 작성
- [ ] errorResponse dto 구현
- [ ] 예외처리에 대한 advice 구현

## Duration
0.5d
